server:
  generic:
    host: localhost
    port: 8080
  instance:
    name: "Quasar"
    caseSensitive: true
    strictRouting: true
  listen:
    enablePrefork: true
    enablePrintRoutes: true

database:
  host: database
  port: 5432
  name: quasar
  username: quasar
  password: quasar-dev